# Generated by Django 3.2.4 on 2021-06-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_type',
        ),
    ]
