# Generated by Django 3.2.4 on 2021-06-04 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210605_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
