# Generated by Django 3.2.4 on 2021-06-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_posts_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
    ]
