# Generated by Django 3.2.4 on 2021-06-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210605_0208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='surname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='lastname',
        ),
    ]
